### ISSUE TITLE
VivosQuilt

### ISSUE THREAD

**Issue by drernie** [data-yaml/vivos#3]
## Parameters

- S3 bucket
- AWS Credentials

## Actions

- track events on .quilt/*
- create QuiltEvents: created, updated

**Comment by drernie** [comment]
https://medium.com/event-driven-utopia/sending-and-receiving-custom-events-with-aws-eventbridge-schema-registry-b73198b7a140
> The best option is to use EventBridge Schema Registry to discover, create, and manage schemas for the events used by both services.

https://github.com/dunithd/edu-samples/blob/main/aws-eventbridge-custom-events/email-service/template.yaml

```yaml
      Events:
        OrderConfirmed:
          Type: CloudWatchEvent # More info about CloudWatchEvent Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent
          Properties:
            EventBusName: custom-event-bus #Uncomment this if your events are not on the 'default' event bus
            Pattern:
              source:
                - edu.svc.orders
              detail-type:
                - Order Confirmed
```
